# Generated by Django 4.2.23 on 2025-11-05 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('phone', 'Phone'), ('sms', 'SMS'), ('email', 'Email'), ('letter', 'Letter'), ('social_media', 'Social Media'), ('in_person', 'In Person'), ('chat', 'Live Chat')], help_text='Communication channel used', max_length=15)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], help_text='Direction of communication', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('follow_up', 'Follow-up Required')], default='completed', help_text='Status of the interaction', max_length=15)),
                ('interaction_date', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField(help_text='Summary of the interaction')),
                ('notes', models.TextField(blank=True, help_text='Additional notes (optional)')),
                ('created_by', models.CharField(blank=True, help_text='User who created this interaction', max_length=100)),
                ('customer', models.ForeignKey(help_text='Customer involved in this interaction', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='customer_management.customer')),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'ordering': ['-interaction_date'],
            },
        ),
    ]
