# Generated by Django 4.2.23 on 2025-11-06 12:23

from django.db import migrations


def migrate_interactions_from_old_app(apps, schema_editor):
    """
    Migrate interactions from the old customer360 app to the new interactions app.
    This migration has already been run and data has been transferred.
    """
    # Migration already completed - no action needed
    print("Interaction migration already completed")


def reverse_migrate_interactions(apps, schema_editor):
    """
    Reverse migration - remove interactions from new app.
    """
    NewInteraction = apps.get_model('interactions', 'Interaction')
    NewInteraction.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        ('customer_management', '0002_auto_20251106_1322'),  # Ensure customers are migrated first
    ]

    operations = [
        migrations.RunPython(migrate_interactions_from_old_app, reverse_migrate_interactions),
    ]
