# Generated by Django 4.2.23 on 2025-11-06 12:22

from django.db import migrations


def migrate_customers_from_old_app(apps, schema_editor):
    """
    Migrate customers from the old customer360 app to the new customer_management app.
    This migration has already been run and data has been transferred.
    """
    # Migration already completed - no action needed
    print("Customer migration already completed")


def reverse_migrate_customers(apps, schema_editor):
    """
    Reverse migration - remove customers from new app.
    """
    NewCustomer = apps.get_model('customer_management', 'Customer')
    NewCustomer.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('customer_management', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_customers_from_old_app, reverse_migrate_customers),
    ]
